# Generated by Django 5.0.2 on 2024-03-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=30)),
                ('list_description', models.CharField(max_length=300)),
                ('list_starting_bid', models.FloatField()),
                ('list_image', models.CharField(max_length=1000)),
                ('list_active', models.BooleanField(verbose_name=True)),
                ('list_catagpry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
            ],
        ),
    ]
