# Generated by Django 5.0.2 on 2024-03-17 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='list_watch_list',
            field=models.ManyToManyField(related_name='watchlist_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
