# Generated by Django 5.0.2 on 2024-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='list_last_upDate',
            field=models.DateField(auto_now=True),
        ),
    ]
