# Generated by Django 5.0.2 on 2024-03-25 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_list_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_commint_balue', models.TextField(max_length=200)),
                ('user_commint_onList', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
                ('user_on_commint', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
